### ISSUE TITLE
Grounding compiler error

### ISSUE THREAD

**Issue by TheRealOutcast1001** [VRLabs/Final-IK-Stub#9]
Made a new project, project wouldn't load into play mode with Final IK Stub due to compiler issue caused by Grounding not found.

![image](https://github.com/VRLabs/Final-IK-Stub/assets/87545251/7dc8e21b-f3db-4cca-89e5-04ac00286629)

![image](https://github.com/VRLabs/Final-IK-Stub/assets/87545251/22245e0a-ae77-461e-aa21-b8d29df1c771)

**Comment by Cibbi** [comment]
That first file should not be there, what version of the stub are you using?

Try to remove the package, wait for unity to reload, and then reinstall the package.

**Comment by TheRealOutcast1001** [comment]
I installed it with VCC, which ive been told is currently not a good way to install it as it causes issues.

**Comment by Cibbi** [comment]
we had an issue with with version 1.9.1, but it was fixed with 1.9.2.

My doubt is that there were 2 versions of the stub installed in your project causing the issue

From the sceenshot i see you have the files from 1.9.2, but also a file (Grounder.cs, the only one that has a different icon there) that should not be there (and it's not on the files of the release, checked it before my first answer) so it must have gotten there by other means

**Comment by jellejurre** [comment]
Please try uninstalling the stub and installing the latest version of the stub, that should fix this. If it doesn't, feel free to open a new issue.
